info:
  app:
    name: zuulserver
    description: Api entrypoint

spring:
  application:
    name: zuulserver
    
server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    catalog-search-service: /catalog/search/**
    catalog-metadata-service: /catalog/metadata/**
    catalog-item-service: /catalog/items/**
    catalog-iiif-presentation-service: /catalog/iiif/**

---
spring:
    profiles: docker
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

zipkin:
    collector-hostname: zipkinCollector