info:
  app:
    name: zuulserver
    description: Api entrypoint

spring:
  application:
    name: zuulserver
    
server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ConnectTimeout: 3000
  ReadTimeout: 5000

zuul:
  routes:
    catalog-search-service:
        path: /catalog/search/**
        stripPrefix: false
    catalog-metadata-service:
        path: /catalog/metadata/**
        stripPrefix: false
    catalog-item-service: 
        path: /catalog/items/**
        stripPrefix: false
    catalog-delivery-service:
        path: /delivery/**
        stripPrefix: false
    catalog-iiif-presentation-service:
        path: /catalog/iiif/**
        stripPrefix: false
    catalog-iiif-content-search:
        path: /catalog/contentsearch/**
        stripPrefix: false
    catalog-reference-service:
        path: /catalog/reference/**
        stripPrefix: false
    catalog-recommend-service:
        path: /catalog/recommend/**
        stripPrefix: false
    catalog-playlist-service:
        path: /catalog/playlist/**
        stripPrefix: false
    dewey-service:
        path: /dewey/**
        stripPrefix: false
    user-service:
        path: /user/**
        stripPrefix: false
    catalog-typeahead-service:
        path: /catalog/typeahead/**
        stripPrefix: false
    streaming-info-service:
        path: /streaming/**
        stripPrefix: false

zipkin:
    collector-hostname: localhost

---
spring:
    profiles: docker
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

zipkin:
    collector-hostname: zipkinCollector