info:
  app:
    name: zuulserver
    description: Api entrypoint

spring:
  application:
    name: zuulserver
    
server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ConnectTimeout: 3000
  ReadTimeout: 5000

zuul:
  routes:
    iiif-image-api:
        path: /services/image/**
        url: http://www.nb.no/services/image
    catalog-metadata-service:
        path: /catalog/v1/metadata/**
        stripPrefix: false
    catalog-item-service-items:
        path: /catalog/v1/items/**
        serviceId: catalog-item-service
        stripPrefix: false
    catalog-item-service-search:
        path: /catalog/v1/search/**
        serviceId: catalog-item-service
        stripPrefix: false
    catalog-delivery-service:
        path: /catalog/v1/delivery/**
        stripPrefix: false
    catalog-iiif-presentation-service:
        path: /catalog/v1/iiif/**
        stripPrefix: false
    catalog-iiif-content-search:
        path: /catalog/v1/contentsearch/**
        stripPrefix: false
    catalog-reference-service:
        path: /catalog/v1/reference/**
        stripPrefix: false
    catalog-search-suggestion-service:
        path: /catalog/v1/searchsuggestions/**
        stripPrefix: false
    catalog-playlist-service:
        path: /catalog/v1/playlist/**
        stripPrefix: false
    dewey-service:
        path: /dewey/v1/**
        stripPrefix: false
    user-service:
        path: /me/v1/**
        stripPrefix: false
    catalog-typeahead-service:
        path: /catalog/v1/typeahead/**
        stripPrefix: false
    streaming-info-service:
        path: /streaming/v1/**
        stripPrefix: false
    catalog-snippet-service:
        path: /catalog/v1/snippet/**
        stripPrefix: false
    catalog-recommendation-service:
        path: /catalog/v1/recommend/**
        stripPrefix: false
    insidesearch-playground:
        path: /insidesearch-playground/**
        stripPrefix: false

zipkin:
    collector-hostname: localhost

---
spring:
    profiles: docker
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

zipkin:
    collector-hostname: zipkinCollector