info:
  app:
    name: zuulserver
    description: Api entrypoint

server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    catalog-search-service: /catalog/search/**
    catalog-metadata-service: /catalog/metadata/**
    catalog-item-service: /catalog/items/**

---
spring:
    profiles: docker
  
zuul:
  routes:
    catalog-search-service: /catalog/search/**
    catalog-metadata-service: /catalog/metadata/**

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
