info:
  app:
    name: zuulserver
    description: Api entrypoint

spring:
  application:
    name: zuulserver
    
server:
  port: 8765

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ConnectTimeout: 3000
  ReadTimeout: 5000

zuul:
  routes:
    iiif-image-api:
        path: /services/image/**
        url: http://www.nb.no/services/image
    catalog-search-service:
        path: /v1/catalog/search/**
        stripPrefix: false
    catalog-metadata-service:
        path: /v1/catalog/metadata/**
        stripPrefix: false
    catalog-item-service: 
        path: /v1/catalog/items/**
        stripPrefix: false
    catalog-delivery-service:
        path: /v1/delivery/**
        stripPrefix: false
    catalog-iiif-presentation-service:
        path: /v1/catalog/iiif/**
        stripPrefix: false
    catalog-iiif-content-search:
        path: /v1/catalog/contentsearch/**
        stripPrefix: false
    catalog-reference-service:
        path: /v1/catalog/reference/**
        stripPrefix: false
    catalog-search-suggestion-service:
        path: /v1/catalog/searchsuggestions/**
        stripPrefix: false
    catalog-playlist-service:
        path: /v1/catalog/playlist/**
        stripPrefix: false
    dewey-service:
        path: /v1/dewey/**
        stripPrefix: false
    user-service:
        path: /v1/me/**
        stripPrefix: false
    catalog-typeahead-service:
        path: /v1/catalog/typeahead/**
        stripPrefix: false
    streaming-info-service:
        path: /v1/streaming/**
        stripPrefix: false
    catalog-snippet-service:
        path: /v1/catalog/snippet/**
        stripPrefix: false
    catalog-recommendation-service:
        path: /v1/catalog/recommend/**
        stripPrefix: false

zipkin:
    collector-hostname: localhost

---
spring:
    profiles: docker
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

zipkin:
    collector-hostname: zipkinCollector